### ISSUE TITLE
Not available for latest dart specification

### ISSUE THREAD

**Issue by srivanigorthi** [BenNG/countdown#1]
Hi,

I was trying to use package in my project. "packages upgrade" is getting error with dependency issue for latest dart version. Please check and do the needful at the earliest to clear the issue.

**Comment by olaray** [comment]
I have created a PR for this issue fixing the issue #2

**Comment by maks** [comment]
@BenNG now that this fix has been merged, would you please be able to publish the updated version 0.1.0 of the package to pub.dartlang.org ?

**Comment by BenNG** [comment]
very sorry for the delay  !
